### ISSUE TITLE
Stuck at FM Disabled

### ISSUE THREAD

**Issue by XLpacman805** [SomeOneUnknown/A3FM#29]
Able to change station when hosted on own machine but not when on a dedicated server.

**Comment by Enclave2020** [comment]
This addon need to be installed on the server too (Include radio stations)
Sorry for long reply

**Comment by XLpacman805** [comment]
I have it loaded on the server but not as a server side mod.

**Comment by Enclave2020** [comment]
Can you upload mod folder from server (with stations)?
I will check it
